/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as ProgresoRouteImport } from './routes/progreso'
import { Route as Paso4RouteImport } from './routes/paso-4'
import { Route as Paso3RouteImport } from './routes/paso-3'
import { Route as Paso2RouteImport } from './routes/paso-2'
import { Route as Paso1RouteImport } from './routes/paso-1'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as IndexRouteImport } from './routes/index'

const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgresoRoute = ProgresoRouteImport.update({
  id: '/progreso',
  path: '/progreso',
  getParentRoute: () => rootRouteImport,
} as any)
const Paso4Route = Paso4RouteImport.update({
  id: '/paso-4',
  path: '/paso-4',
  getParentRoute: () => rootRouteImport,
} as any)
const Paso3Route = Paso3RouteImport.update({
  id: '/paso-3',
  path: '/paso-3',
  getParentRoute: () => rootRouteImport,
} as any)
const Paso2Route = Paso2RouteImport.update({
  id: '/paso-2',
  path: '/paso-2',
  getParentRoute: () => rootRouteImport,
} as any)
const Paso1Route = Paso1RouteImport.update({
  id: '/paso-1',
  path: '/paso-1',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/historial': typeof HistorialRoute
  '/paso-1': typeof Paso1Route
  '/paso-2': typeof Paso2Route
  '/paso-3': typeof Paso3Route
  '/paso-4': typeof Paso4Route
  '/progreso': typeof ProgresoRoute
  '/resultados': typeof ResultadosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/historial': typeof HistorialRoute
  '/paso-1': typeof Paso1Route
  '/paso-2': typeof Paso2Route
  '/paso-3': typeof Paso3Route
  '/paso-4': typeof Paso4Route
  '/progreso': typeof ProgresoRoute
  '/resultados': typeof ResultadosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/historial': typeof HistorialRoute
  '/paso-1': typeof Paso1Route
  '/paso-2': typeof Paso2Route
  '/paso-3': typeof Paso3Route
  '/paso-4': typeof Paso4Route
  '/progreso': typeof ProgresoRoute
  '/resultados': typeof ResultadosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/historial'
    | '/paso-1'
    | '/paso-2'
    | '/paso-3'
    | '/paso-4'
    | '/progreso'
    | '/resultados'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/historial'
    | '/paso-1'
    | '/paso-2'
    | '/paso-3'
    | '/paso-4'
    | '/progreso'
    | '/resultados'
  id:
    | '__root__'
    | '/'
    | '/historial'
    | '/paso-1'
    | '/paso-2'
    | '/paso-3'
    | '/paso-4'
    | '/progreso'
    | '/resultados'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistorialRoute: typeof HistorialRoute
  Paso1Route: typeof Paso1Route
  Paso2Route: typeof Paso2Route
  Paso3Route: typeof Paso3Route
  Paso4Route: typeof Paso4Route
  ProgresoRoute: typeof ProgresoRoute
  ResultadosRoute: typeof ResultadosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progreso': {
      id: '/progreso'
      path: '/progreso'
      fullPath: '/progreso'
      preLoaderRoute: typeof ProgresoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paso-4': {
      id: '/paso-4'
      path: '/paso-4'
      fullPath: '/paso-4'
      preLoaderRoute: typeof Paso4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paso-3': {
      id: '/paso-3'
      path: '/paso-3'
      fullPath: '/paso-3'
      preLoaderRoute: typeof Paso3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paso-2': {
      id: '/paso-2'
      path: '/paso-2'
      fullPath: '/paso-2'
      preLoaderRoute: typeof Paso2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paso-1': {
      id: '/paso-1'
      path: '/paso-1'
      fullPath: '/paso-1'
      preLoaderRoute: typeof Paso1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial': {
      id: '/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof HistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistorialRoute: HistorialRoute,
  Paso1Route: Paso1Route,
  Paso2Route: Paso2Route,
  Paso3Route: Paso3Route,
  Paso4Route: Paso4Route,
  ProgresoRoute: ProgresoRoute,
  ResultadosRoute: ResultadosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
